name: Release

on:
  push:
    tags:
      - snapshot
      - v*
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            TEST_TASK: jvmTest linuxX64Test
          - os: windows-latest
            TEST_TASK: mingwX64Test
    runs-on: ${{matrix.os}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Run tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: ${{matrix.TEST_TASK}}
        cache-read-only: ${{ github.ref != 'refs/tags/snapshot' }}
    - name: Bundle the build report
      if: failure()
      run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
    - name: Upload the build report
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: error-report
        path: build-reports.zip
  publish:
    needs: test
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: macosX64Test
          cache-read-only: ${{ github.ref != 'refs/tags/snapshot' }}
      - name: Publish
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publishToSonatype
          cache-read-only: ${{ github.ref != 'refs/tags/snapshot' }}
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
      - name: Bundle the build report
        if: failure()
        run: find . -type d -name 'reports' | zip -@ -r build-reports.zip
      - name: Upload the build report
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: error-report
          path: build-reports.zip